import Head from 'next/head';

import Gallery from '../src/layouts/Gallery';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Wasatch Bicycles</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Gallery />
			</main>
		</div>
	);
}
